DEF DISPCONT(FILENAME, ENC):
    TEMP= FILENAME.SPLIT("/")
    PRINT("\N\N====================================\N{}\N====================================".FORMAT(TEMP[-1]))
    FS = OPEN(FILENAME, "RT", ENCODING=ENC )
    TXT = FS.READ()
    FS.CLOSE()
    PRINT("CONTENTS:[\N{}]".FORMAT(TXT))
    PRINT("SIZE:{}".FORMAT(LEN(TXT)))

    FS = OPEN(FILENAME, "RB" )
    BIN = FS.READ()
    FS.CLOSE()
    PRINT("CONTENTS:[", END="")
    PRINT(BIN, "]")
    PRINT("SIZE:{}".FORMAT(LEN(BIN)))
   

FILE_UTF8 = "6_FILE_AND_DATA_FORMAT/TXT_UTF8.TXT"
FILE_GBK = "6_FILE_AND_DATA_FORMAT/TXT_GBK.TXT"
FILE_UNICODE = "6_FILE_AND_DATA_FORMAT/TXT_UNICODE.TXT"

DISPCONT( FILE_UTF8, "UTF-8")

DISPCONT( FILE_UNICODE, "UTF-16")

DISPCONT( FILE_GBK, "GBK")

